name: 'Calculate Version'
description: 'Determines version using GitVersion and writes it to .tags file'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  prod:
    description: 'Flag indicating whether production is true'
    required: true
    default: 'false'
outputs:
  version:
    description: 'The version determined by GitVersion'
